# Ghostty integration
source "${GHOSTTY_RESOURCES_DIR}/shell-integration/zsh/ghostty-integration"

export EDITOR="nvim"
export VISUAL="nvim"

# Aliases
alias ls='ls --color=auto'
alias c4='clang++ -std=c++2a'
alias E='exit'
alias vim='nvim'

# yazi
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd < "$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

# Autocompletion + syntax highlighting
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ZSH Prompt
source /usr/local/share/powerlevel10k/powerlevel10k.zsh-theme
